---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - common

- name: Upgrade all base packages
  apt: upgrade=dist
  tags:
    - common

- name: Clean out old packages if any
  command: apt-get -y autoremove
  tags:
    - common

# Some npm (and other tools) install's can need this at times
- name: Install build-essential
  apt: name={{ item }} state=present
  with_items:
    - build-essential
  tags:
    - common

# Some pip's can use this at times
- name: Install python-dev
  apt: name={{ item }} state=present
  with_items:
    - python-dev
  tags:
    - common

- name: Install python pip
  apt: name={{ item }} state=present
  with_items:
    - python-pip
  tags:
    - common

# Some gems can use this at times
- name: Install ruby-dev
  apt: name={{ item }} state=present
  with_items:
    - ruby-dev
  tags:
    - common

- name: Install wget
  apt: name={{ item }} state=present
  with_items:
    - wget
  tags:
    - common

- name: Install curl
  apt: name={{ item }} state=present
  with_items:
    - curl
  tags:
    - common

- name: Install unzip
  apt: name={{ item }} state=present
  with_items:
    - unzip
  tags:
    - common

- name: Install imagemagick
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
  tags:
    - common

- name: Install graphviz
  apt: name={{ item }} state=present
  with_items:
    - graphviz
  tags:
    - common

# Useful if your application needs to check the environment it's running on
- name: Export APPLICATION_ENV in .profile
  sudo_user: vagrant
  lineinfile: >
    dest="~/.profile"
    line="export APPLICATION_ENV=local"
  tags:
    - common
