---
- name: Copy Acquia Cloud API
  copy:
    src: "{{ acquia_insight_capi }}/.acquia"
    dest: /home/vagrant
  tags:
    - acquia_insight

- name: Copy drush aliases
  copy:
    src: "{{ acquia_insight_capi }}/.drush/"
    dest: /home/vagrant/.drush
  tags:
    - acquia_insight

- name: Update drush commands
  command: drush cc drush
  tags:
    - acquia_insight

# - name: Update Drush aliases for all accessible Acquia Cloud sites
#   command: drush acquia-update
#   tags:
#     - acquia_insight
