---
- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755
  tags:
    - composer

- name: Create a COMPOSER_HOME directory
  file: path={{ composer_home }} state=directory
  tags:
    - composer

- name: Create a COMPOSER_VENDOR_DIR directory
  file: path={{ composer_home }}/vendor state=directory
  tags:
    - composer

- name: Set COMPOSER_HOME environment variable
  lineinfile:
    line: 'COMPOSER_HOME="{{ composer_home }}"'
    dest: /etc/environment
    state: present
    insertafter: EOF
  tags:
    - composer

- name: Set COMPOSER_BIN_DIR environment variable
  lineinfile:
    line: 'COMPOSER_BIN_DIR="/usr/local/bin"'
    dest: /etc/environment
    state: present
    insertafter: EOF
  tags:
    - composer

- name: Set COMPOSER_VENDOR_DIR environment variable
  lineinfile:
    line: 'COMPOSER_VENDOR_DIR="{{ composer_home }}/vendor"'
    dest: /etc/environment
    state: present
    insertafter: EOF
  tags:
    - composer
