---
- name: Download Drupal 7
  get_url: url=http://ftp.drupal.org/files/projects/drupal-7.40.tar.gz dest=/tmp
  tags:
    - drupal7

- name: Decompress D7 tarball
  shell: tar zxvf /tmp/drupal-7.40.tar.gz -C /tmp
  tags:
    - drupal7

- name: Move D7 to project docroot
  shell: "mv /tmp/drupal-7.40/* {{ project_docroot }}; mv /tmp/drupal-7.40/.* {{ project_docroot }}"
  ignore_errors: yes
  tags:
    - drupal7

- name: Clean up - Delete D7 tarball
  shell: "rm -f /tmp/drupal-7.40.tar.gz; rm -rf /tmp/drupal-7.40"
  tags:
    - drupal7

- name: Unlock file permissions before-install
  ignore_errors: yes
  shell: chmod 777 {{ item }}
  with_items:
    -  "{{ project_docroot }}/sites/default"
  tags:
    - drupal7

- name: Install D7 Minimal Site
  command: drush -y si minimal --db-url=mysql://root:@localhost/{{ project_name }} --site-name={{ project_name }} --account-name=admin --account-pass=admin --account-mail='vagrant@localhost.local' --notify=global
  run_once: true
  ignore_errors: yes
  args:
    chdir: "{{ project_docroot }}"
  tags:
    - drupal7

# Install Coding Standards tools here or perhaps on the host via bootstrap?
