---
- name: Install git
  apt: name={{ item }} state=present
  with_items:
    - git-core
    - git
  tags:
    - git

- name: Copy .gitconfig
  copy:
    src: "{{ user_gitconfig }}"
    dest: /home/vagrant/.gitconfig
    mode: 0644
    force: yes
  tags:
    - git

- name: Validate .gitconfig permissions
  command: chmod 644 /home/vagrant/.gitconfig
  tags:
    - git
